# Generated by Django 4.1.4 on 2023-01-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
